// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIAccountPanel
    {
        
        public const string NAME = "UIAccountPanel";
        
        [SerializeField()]
        public Button Background;
        
        [SerializeField()]
        public Button btnClose;
        
        [SerializeField()]
        public Text TxtID;
        
        [SerializeField()]
        public Text TxtUsername;
        
        [SerializeField()]
        public Button BtnCopyID;
        
        [SerializeField()]
        public Button BtnChangeName;
        
        [SerializeField()]
        public Button BtnQQ;
        
        [SerializeField()]
        public Button BtnFacebook;
        
        [SerializeField()]
        public Button BtnChangeAccount;
        
        private UIAccountPanelData mPrivateData = null;
        
        public UIAccountPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIAccountPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Background = null;
            btnClose = null;
            TxtID = null;
            TxtUsername = null;
            BtnCopyID = null;
            BtnChangeName = null;
            BtnQQ = null;
            BtnFacebook = null;
            BtnChangeAccount = null;
            mData = null;
        }
    }
}
