// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    using UniRx;
    
    public class UIAddInventoryPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIAddInventoryPanel : QFramework.UIPanel
    {
        protected override void RegisterUIEvent()
        {
            UITopStatus.BtnClose.OnClickAsObservable().Subscribe(_ =>
            {
                CloseSelf();
            });

            BtnAdd.OnClickAsObservable().Subscribe(_ =>
            {

                if (GameData.GemCount >= int.Parse(TxtUseGem.text))
                {
                    CloseSelf();
                    // 减少钻石
                    GameData.GemCount = GameData.GemCount - int.Parse(TxtUseGem.text);
                    // 增加背包数量
                    GameData.InventoryCount = GameData.InventoryCount + 10;
                    // 更新钻石，金币UI
                    UIMgr.GetPanel<UIInventoryNewPanel>().UpdateTopStautsValue();

                    // 更新背包界面显示背包列表
                    UIMgr.GetPanel<UIInventoryNewPanel>().ShowAddNewInventoryList();
                    UIMgr.GetPanel<UIInventoryNewPanel>().ShowUsedTextCount();

                    // 跳转到成功界面
                    UIMgr.OpenPanel<UIDataUpdateSucceedPanel>(new UIDataUpdateSucceedPanelData
                    {
                        SuccessModel = new DataUpdateSuccessModel
                        {
                            StrTitle = "恭喜您",
                            StrDesc = "获得10个背包格子",
                            IsSucceed = true
                        }
                    });
                }
                else
                {
                    // 跳转到失败界面
                    UIMgr.OpenPanel<UIDataUpdateSucceedPanel>(new UIDataUpdateSucceedPanelData
                    {
                        SuccessModel = new DataUpdateSuccessModel
                        {
                            StrTitle = "失败了",
                            StrDesc = "没有足够的钻石哦~",
                            IsSucceed = false
                        }
                    });
                }


            });




        }
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIAddInventoryPanelData ?? new UIAddInventoryPanelData();
            // please add init code here
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
