// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    using UniRx;

    public class DataUpdateSuccessModel
    {
        /// <summary>
        /// 标题
        /// </summary>
        public string StrTitle { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string StrDesc { get; set; }

        /// <summary>
        /// 是否成功
        /// </summary>
        /// <value><c>true</c> if is succeed; otherwise, <c>false</c>.</value>
        public bool IsSucceed { get; set; }
    }


    public class UIDataUpdateSucceedPanelData : QFramework.UIPanelData
    {
        public DataUpdateSuccessModel SuccessModel;
    }
    
    public partial class UIDataUpdateSucceedPanel : QFramework.UIPanel
    {
        protected override void RegisterUIEvent()
        {
            BtnClose.OnClickAsObservable().Subscribe(_ =>
            {
                CloseSelf();
            });

            BtnOK.OnClickAsObservable().Subscribe(_ =>
            {
                CloseSelf();
            });
        }
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIDataUpdateSucceedPanelData ?? new UIDataUpdateSucceedPanelData();
            // please add init code here

            TxtTile.text = mData.SuccessModel.StrTitle;
            TxtDesc.text = mData.SuccessModel.StrDesc;
            if (mData.SuccessModel.IsSucceed)
            {
                ImgTitle.sprite = Resources.Load<Sprite>("Images/MsgSucceed");
            }
            else
            {
                ImgTitle.sprite = Resources.Load<Sprite>("Images/MsgFailure"); 
            }
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
