// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIDataUpdateSucceedPanel
    {
        
        public const string NAME = "UIDataUpdateSucceedPanel";
        
        // 失败成功图片
        [SerializeField()]
        public Image ImgTitle;
        
        [SerializeField()]
        public Text TxtTile;
        
        [SerializeField()]
        public Button BtnClose;
        
        [SerializeField()]
        public Text TxtDesc;
        
        [SerializeField()]
        public Button BtnOK;
        
        private UIDataUpdateSucceedPanelData mPrivateData = null;
        
        public UIDataUpdateSucceedPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIDataUpdateSucceedPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ImgTitle = null;
            TxtTile = null;
            BtnClose = null;
            TxtDesc = null;
            BtnOK = null;
            mData = null;
        }
    }
}
