// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    using UniRx;
    
    public class UIFreeRewardPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIFreeRewardPanel : QFramework.UIPanel
    {
        protected override void RegisterUIEvent()
        {
            BtnClose.OnClickAsObservable().Subscribe(_ =>
            {
                CloseSelf();
            });

            Background.OnClickAsObservable().Subscribe(_ =>
            {
                CloseSelf();
            });

            BtnWatch.OnClickAsObservable().Subscribe(_ =>
            {
                Debug.Log("观看广告，获取奖励！");
            });

            BtnShare.OnClickAsObservable().Subscribe(_ =>
            {
                Debug.Log("分享游戏，获取奖励");
            });
        }
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIFreeRewardPanelData ?? new UIFreeRewardPanelData();
            // please add init code here
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
