// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    using UniRx;
    
    public class UIGamePanelData : QFramework.UIPanelData
    {
        //public bool ShowCharacters = true; 
    }
    
    public partial class UIGamePanel : QFramework.UIPanel
    {
        protected override void RegisterUIEvent()
        {
            BtnPause.OnClickAsObservable().Subscribe(_ =>
            {
                Debug.Log("BtnPause clicked!");

                Transform.Find("Characters").gameObject.SetActive(false);
                Transform.Find("Emenys").gameObject.SetActive(false);
                UIMgr.OpenPanel<UIGamePausePanel>();
            });

            BtnProps.OnClickAsObservable().Subscribe(_ =>
            {
                Debug.Log("BtnProps clicked!");
            });

            BtnAuto.OnClickAsObservable().Subscribe(_ =>
            {
                Debug.Log("BtnAuto clicked!");
            });

            Btn2Speed.OnClickAsObservable().Subscribe(_ =>
            {
                Debug.Log("Btn2Speed clicke!");
            });
        }
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIGamePanelData ?? new UIGamePanelData();
            // please add init code here
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
