// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIGamePausePanel
    {
        
        public const string NAME = "UIGamePausePanel";
        
        // 继续游戏按钮
        [SerializeField()]
        public Button BtnContinue;
        
        // 重新开始按钮
        [SerializeField()]
        public Button BtnRestart;
        
        // 放弃战斗
        [SerializeField()]
        public Button BtnGiveUp;
        
        // 设置按钮
        [SerializeField()]
        public Button BtnSetting;
        
        private UIGamePausePanelData mPrivateData = null;
        
        public UIGamePausePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGamePausePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnContinue = null;
            BtnRestart = null;
            BtnGiveUp = null;
            BtnSetting = null;
            mData = null;
        }
    }
}
