// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIGamePanel
    {
        
        public const string NAME = "UIGamePanel";
        
        // 工具按钮
        [SerializeField()]
        public Button BtnProps;
        
        // 自动战斗按钮
        [SerializeField()]
        public Button BtnAuto;
        
        // 2倍速按钮
        [SerializeField()]
        public Button Btn2Speed;
        
        // 暂停按钮
        [SerializeField()]
        public Button BtnPause;
        
        // 获取的金币
        [SerializeField()]
        public Text TxtGoldNum;
        
        // 获取的经验
        [SerializeField()]
        public Text TxtExpNum;
        
        private UIGamePanelData mPrivateData = null;
        
        public UIGamePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGamePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnProps = null;
            BtnAuto = null;
            Btn2Speed = null;
            BtnPause = null;
            TxtGoldNum = null;
            TxtExpNum = null;
            mData = null;
        }
    }
}
