// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIInventoryItemPanel
    {
        
        public const string NAME = "UIInventoryItemPanel";
        
        [SerializeField()]
        public UITopStatus UITopStatus;
        
        [SerializeField()]
        public Image ItemPanel;
        
        [SerializeField()]
        public Image ImgItem;
        
        [SerializeField()]
        public Button BtnSell;
        
        [SerializeField()]
        public Button BtnUpgrade;
        
        [SerializeField()]
        public Text ItemDesc;
        
        [SerializeField()]
        public Image SelectNumPanel;
        
        [SerializeField()]
        public Button BtnMin;
        
        [SerializeField()]
        public Button BtnLess;
        
        [SerializeField()]
        public Text TxtNum;
        
        [SerializeField()]
        public Button BtnMore;
        
        [SerializeField()]
        public Button BtnMax;
        
        [SerializeField()]
        public Text TxtNumDesc;
        
        [SerializeField()]
        public Button BtnSelectSell;
        
        [SerializeField()]
        public Button BtnSelectCancel;
        
        [SerializeField()]
        public Image SellConfirmPanel;
        
        // 失败成功图片
        [SerializeField()]
        public Image ImgTitle;
        
        [SerializeField()]
        public Text TxtTile;
        
        [SerializeField()]
        public Text TxtDesc;
        
        [SerializeField()]
        public Button BtnConfirmOK;
        
        [SerializeField()]
        public Button BtnConfirmCancel;
        
        private UIInventoryItemPanelData mPrivateData = null;
        
        public UIInventoryItemPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIInventoryItemPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UITopStatus = null;
            ItemPanel = null;
            ImgItem = null;
            BtnSell = null;
            BtnUpgrade = null;
            ItemDesc = null;
            SelectNumPanel = null;
            BtnMin = null;
            BtnLess = null;
            TxtNum = null;
            BtnMore = null;
            BtnMax = null;
            TxtNumDesc = null;
            BtnSelectSell = null;
            BtnSelectCancel = null;
            SellConfirmPanel = null;
            ImgTitle = null;
            TxtTile = null;
            TxtDesc = null;
            BtnConfirmOK = null;
            BtnConfirmCancel = null;
            mData = null;
        }
    }
}
