// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    using UniRx;
    
    public class UIInventoryItemPanelData : QFramework.UIPanelData
    {
        public Item item;
    }
    
    public partial class UIInventoryItemPanel : QFramework.UIPanel
    {
        protected override void RegisterUIEvent()
        {
            UITopStatus.BtnClose.OnClickAsObservable().Subscribe(_ =>
            {
                CloseSelf();
            });
        }

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIInventoryItemPanelData ?? new UIInventoryItemPanelData();
            // please add init code here

            TxtItemDes.text = mData.item.Name;
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
