// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIInventoryItemPanel
    {
        
        public const string NAME = "UIInventoryItemPanel";
        
        [SerializeField()]
        public UITopStatus UITopStatus;
        
        [SerializeField()]
        public Image ImgItem;
        
        [SerializeField()]
        public Button BtnSell;
        
        [SerializeField()]
        public Button BtnUpgrade;
        
        [SerializeField()]
        public Text ItemDesc;
        
        private UIInventoryItemPanelData mPrivateData = null;
        
        public UIInventoryItemPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIInventoryItemPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UITopStatus = null;
            ImgItem = null;
            BtnSell = null;
            BtnUpgrade = null;
            ItemDesc = null;
            mData = null;
        }
    }
}
