// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UILoginPanel
    {
        
        public const string NAME = "UILoginPanel";
        
        [SerializeField()]
        public Button Background;
        
        [SerializeField()]
        public Button BtnClose;
        
        [SerializeField()]
        public Button BtnSignup;
        
        [SerializeField()]
        public Button BtnForgot;
        
        [SerializeField()]
        public Button BtnLogin;
        
        [SerializeField()]
        public Text TxtPhoneNum;
        
        [SerializeField()]
        public Text TxtPassword;
        
        [SerializeField()]
        public Toggle CBoxRemember;
        
        private UILoginPanelData mPrivateData = null;
        
        public UILoginPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UILoginPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Background = null;
            BtnClose = null;
            BtnSignup = null;
            BtnForgot = null;
            BtnLogin = null;
            TxtPhoneNum = null;
            TxtPassword = null;
            CBoxRemember = null;
            mData = null;
        }
    }
}
