// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIMapStagesPanel
    {
        
        public const string NAME = "UIMapStagesPanel";
        
        [SerializeField()]
        public Button BtnBack;
        
        [SerializeField()]
        public Button BtnGoldAdd;
        
        [SerializeField()]
        public Button BtnGemAdd;
        
        [SerializeField()]
        public Button StageCompleteStar3;
        
        [SerializeField()]
        public Button StageDefault;
        
        [SerializeField()]
        public Button StageLock;
        
        private UIMapStagesPanelData mPrivateData = null;
        
        public UIMapStagesPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIMapStagesPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnBack = null;
            BtnGoldAdd = null;
            BtnGemAdd = null;
            StageCompleteStar3 = null;
            StageDefault = null;
            StageLock = null;
            mData = null;
        }
    }
}
