// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIMapStatesDesPanel
    {
        
        public const string NAME = "UIMapStatesDesPanel";
        
        [SerializeField()]
        public Button Background;
        
        [SerializeField()]
        public Button BtnClose;
        
        [SerializeField()]
        public Button BtnStart;
        
        private UIMapStatesDesPanelData mPrivateData = null;
        
        public UIMapStatesDesPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIMapStatesDesPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Background = null;
            BtnClose = null;
            BtnStart = null;
            mData = null;
        }
    }
}
