// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiazDTRPG
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIRegisterPanel
    {
        
        public const string NAME = "UIRegisterPanel";
        
        [SerializeField()]
        public Button Background;
        
        [SerializeField()]
        public Button BtnClose;
        
        [SerializeField()]
        public Button BtnSignin;
        
        [SerializeField()]
        public Button BtnSignUp;
        
        [SerializeField()]
        public Text TxtPhoneNum;
        
        [SerializeField()]
        public Text TxtUsername;
        
        [SerializeField()]
        public Text TxtPassword;
        
        private UIRegisterPanelData mPrivateData = null;
        
        public UIRegisterPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIRegisterPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Background = null;
            BtnClose = null;
            BtnSignin = null;
            BtnSignUp = null;
            TxtPhoneNum = null;
            TxtUsername = null;
            TxtPassword = null;
            mData = null;
        }
    }
}
